import { Timezone } from './types';

export const TIMEZONES: Timezone[] = [
  { iana: 'Africa/Cairo', city: 'Cairo', country: 'Egypt', lat: 30.04, lon: 31.23 },
  { iana: 'Africa/Johannesburg', city: 'Johannesburg', country: 'South Africa', lat: -26.20, lon: 28.04 },
  { iana: 'Africa/Lagos', city: 'Lagos', country: 'Nigeria', lat: 6.52, lon: 3.37 },
  { iana: 'America/Argentina/Buenos_Aires', city: 'Buenos Aires', country: 'Argentina', lat: -34.60, lon: -58.38 },
  { iana: 'America/Chicago', city: 'Chicago', country: 'USA', lat: 41.88, lon: -87.63 },
  { iana: 'America/Denver', city: 'Denver', country: 'USA', lat: 39.74, lon: -104.99 },
  { iana: 'America/Los_Angeles', city: 'Los Angeles', country: 'USA', lat: 34.05, lon: -118.24 },
  { iana: 'America/Mexico_City', city: 'Mexico City', country: 'Mexico', lat: 19.43, lon: -99.13 },
  { iana: 'America/New_York', city: 'New York', country: 'USA', lat: 40.71, lon: -74.00 },
  { iana: 'America/Phoenix', city: 'Phoenix', country: 'USA', lat: 33.45, lon: -112.07 },
  { iana: 'America/Sao_Paulo', city: 'São Paulo', country: 'Brazil', lat: -23.55, lon: -46.63 },
  { iana: 'America/Toronto', city: 'Toronto', country: 'Canada', lat: 43.65, lon: -79.38 },
  { iana: 'America/Vancouver', city: 'Vancouver', country: 'Canada', lat: 49.28, lon: -123.12 },
  { iana: 'Asia/Bangkok', city: 'Bangkok', country: 'Thailand', lat: 13.75, lon: 100.50 },
  { iana: 'Asia/Dubai', city: 'Dubai', country: 'U.A.E.', lat: 25.20, lon: 55.27 },
  { iana: 'Asia/Hong_Kong', city: 'Hong Kong', country: 'Hong Kong', lat: 22.31, lon: 114.16 },
  { iana: 'Asia/Jakarta', city: 'Jakarta', country: 'Indonesia', lat: -6.20, lon: 106.84 },
  { iana: 'Asia/Kolkata', city: 'Kolkata', country: 'India', lat: 22.57, lon: 88.36 },
  { iana: 'Asia/Seoul', city: 'Seoul', country: 'South Korea', lat: 37.56, lon: 126.97 },
  { iana: 'Asia/Shanghai', city: 'Shanghai', country: 'China', lat: 31.23, lon: 121.47 },
  { iana: 'Asia/Singapore', city: 'Singapore', country: 'Singapore', lat: 1.35, lon: 103.81 },
  { iana: 'Asia/Tokyo', city: 'Tokyo', country: 'Japan', lat: 35.68, lon: 139.69 },
  { iana: 'Australia/Brisbane', city: 'Brisbane', country: 'Australia', lat: -27.46, lon: 153.02 },
  { iana: 'Australia/Melbourne', city: 'Melbourne', country: 'Australia', lat: -37.81, lon: 144.96 },
  { iana: 'Australia/Perth', city: 'Perth', country: 'Australia', lat: -31.95, lon: 115.86 },
  { iana: 'Australia/Sydney', city: 'Sydney', country: 'Australia', lat: -33.86, lon: 151.20 },
  { iana: 'Europe/Amsterdam', city: 'Amsterdam', country: 'Netherlands', lat: 52.36, lon: 4.90 },
  { iana: 'Europe/Berlin', city: 'Berlin', country: 'Germany', lat: 52.52, lon: 13.40 },
  { iana: 'Europe/Brussels', city: 'Brussels', country: 'Belgium', lat: 50.85, lon: 4.35 },
  { iana: 'Europe/Dublin', city: 'Dublin', country: 'Ireland', lat: 53.34, lon: -6.26 },
  { iana: 'Europe/Helsinki', city: 'Helsinki', country: 'Finland', lat: 60.16, lon: 24.93 },
  { iana: 'Europe/Istanbul', city: 'Istanbul', country: 'Turkey', lat: 41.00, lon: 28.97 },
  { iana: 'Europe/Kiev', city: 'Kyiv', country: 'Ukraine', lat: 50.45, lon: 30.52 },
  { iana: 'Europe/London', city: 'London', country: 'UK', lat: 51.50, lon: -0.12 },
  { iana: 'Europe/Madrid', city: 'Madrid', country: 'Spain', lat: 40.41, lon: -3.70 },
  { iana: 'Europe/Moscow', city: 'Moscow', country: 'Russia', lat: 55.75, lon: 37.61 },
  { iana: 'Europe/Oslo', city: 'Oslo', country: 'Norway', lat: 59.91, lon: 10.75 },
  { iana: 'Europe/Paris', city: 'Paris', country: 'France', lat: 48.85, lon: 2.35 },
  { iana: 'Europe/Prague', city: 'Prague', country: 'Czech Republic', lat: 50.07, lon: 14.43 },
  { iana: 'Europe/Rome', city: 'Rome', country: 'Italy', lat: 41.90, lon: 12.49 },
  { iana: 'Europe/Stockholm', city: 'Stockholm', country: 'Sweden', lat: 59.32, lon: 18.06 },
  { iana: 'Europe/Vienna', city: 'Vienna', country: 'Austria', lat: 48.20, lon: 16.37 },
  { iana: 'Europe/Warsaw', city: 'Warsaw', country: 'Poland', lat: 52.22, lon: 21.01 },
  { iana: 'Europe/Zurich', city: 'Zurich', country: 'Switzerland', lat: 47.37, lon: 8.54 },
  { iana: 'Pacific/Auckland', city: 'Auckland', country: 'New Zealand', lat: -36.84, lon: 174.76 },
  { iana: 'Pacific/Honolulu', city: 'Honolulu', country: 'USA', lat: 21.30, lon: -157.85 },
];